spring:
  application:
    name: demo
    version: 0.0.1
  profiles.active: local

---
spring:
  profiles: local

  datasource:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:postgresql://localhost/todo?useUnicode=true&characterEncoding=utf8
    username: postgres
    password: postgres

  jpa:
    generate-ddl: true

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
